### ISSUE TITLE
Glavni ključi

### ISSUE THREAD

**Issue by jaanos** [StonyTark/glasbena-baza#3]
Opažam, da v veznih tabelah nimata nastavljenih glavnih ključev - ti naj sestojijo kar iz obeh referenc.

Če lahko posamezna oseba pri posamezni izdaji sodeluje v več vlogah, potem pri tabeli `Je_sodeloval` v glavni ključ vključita tudi stolpec `vloga`. V tem primeru bi vama svetoval, da za vloge naredita šifrant (torej tabelo z ID-ji in imeni vlog - na slednjem stolpcu imata lahko določilo `UNIQUE`), stolpec `vloga` pa naj bo potem referenca nanj.

**Comment by reflektor25** [comment]
Popravljeno, upam da sem prav razumel. Torej tabela Je_sodeloval ima sedaj trojni sestavljen ključ.

**Comment by jaanos** [comment]
Tako, ja. Kot rečeno, bi vseeno svetoval, da imata v tabeli `Vloga` za glavni ključ številski ID (najbolje z `AUTOINCREMENT`), na katerega se potem seveda sklicujeta (tako se izogneta tekstovnemu ključu).

**Comment by reflektor25** [comment]
Popravljeno tudi to, hvala za opozorilo!
