### ISSUE TITLE
Nalaganje delčkov html kode iz zunanjih datotek

### ISSUE THREAD

**Issue by reflektor25** [StonyTark/glasbena-baza#4]
Zanima me, če obstaja kakšna opcija za nalaganje in prikaz zunanjih html datotek (torej da bi na nek način uvozil samo formo iz drugega dokumenta prek javascript). Trenutno imam celotno zadevo zapisano v javascript spremenljivki , kar se mi ne zdi idealna rešitev (sklicujem se konkretno na dodaj.html datoteko). 
Sem poiskusil že par rešitev iz spletnih forumov (jquery load, <object>) pa mi nikakor ne uspe.

**Comment by jaanos** [comment]
Načeloma je mogoče formo imeti v enem skritem `<div>`u, pa jo potem na želeno (vidno) mesto postavita preko atributa `innerHTML`. Sicer pa ne vidim razloga, da ne bi enostavno imela vsakega obrazca na svoji strani (tj., vsak s svojo potjo in predlogo - tako bo tudi strežniška logika enostavnejša in bolj berljiva).

Če vaju skrbi, da bi se koda preveč ponavljala, si lahko pomagata z `rebase` - npr. v `dodaj_osebo.html` (in ostalih obrazcih) imata lahko `% rebase('dodaj.html')`, v slednjem pa pustita `% rebase('osnova.html')`.

**Comment by reflektor25** [comment]
Hvala za odgovor!
